plugins = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\toonz\\OneDrive\\Desktop\\NexVault"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"
X-XSS-Protection = "1; mode=block"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
Content-Security-Policy = "upgrade-insecure-requests"

[[headers]]
for = "/nv-design.css"

[headers.values]
Cache-Control = "no-cache, must-revalidate"

[[headers]]
for = "/nv-core.js"

[headers.values]
Cache-Control = "no-cache, must-revalidate"

[[headers]]
for = "/nv-canvas.js"

[headers.values]
Cache-Control = "no-cache, must-revalidate"

[[redirects]]
from = "https://www.nexvault.one/*"
to = "https://nexvault.one/:splat"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/about"
to = "/about.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/security"
to = "/security.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/app"
to = "/app.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/mobile"
to = "/nexvault-mobile.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/dev"
to = "/dev-dashboard.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/news"
to = "/news.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/post"
to = "/post.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/terms"
to = "/terms.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/proof"
to = "/proof.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/whitepaper"
to = "/whitepaper.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]